start_time = "2008-07-01T00:00:00"
end_time = "2008-07-07T00:00:00"
time_step = 60 # seconds
integrator = "euler"
edges_file = "example/edges.csv"
initials_file = "example/initials.csv"
parameters_file = "example/parameters.csv"

[globals]
v_0 = 0.33 # m/s
lambda_1 = 0.2
lambda_2 = -0.1
Hu = 0.1 # 100 mm
infiltration = 1.38e-6 # 5 mm/hr
percolation = 5.55e-7 # 2 mm/hr
alpha2 = 0.2 #  surf_vel[m/s]
alpha3 = 259200 # 3 days in seconds
alpha4 = 8640000 # 100 days in seconds
melt_factor = 5.78e-8 # 5.0 mm/day/celsius -> m/s/celsius
temp_thres = 0.0 # temp_threshold[celsius]
